var App = {
  db: null,
  auth: null,
  ticketsRef: null,
  mainTicketsRef: null,
  sprintTicketsRef: null,
  automationTeamsRef: null,
  automationSubteamsRef: null,
  teamRef: null,
  activityRef: null,
  whitelistRef: null,
  ADMIN_EMAIL: 'aaron.delmo@spxexpress.com',
  COLORS: ['#7c6ff7','#6fd4a8','#f7a86f','#6fa8f7','#f7706f','#f7d46f','#b86ff7'],
  allTickets: {},
  mainTickets: {},
  sprintTickets: {},
  automationTeams: {},
  automationSubteams: {},
  hierarchySelectedTeam: '',
  hierarchyEditTarget: null,
  currentProjectView: 'main',
  whitelist: {},
  activityData: {},
  teamMembers: [],
  currentFilter: 'active',
  currentPriorityFilter: 'all',
  currentContrib: 'all',
  currentVibeView: 'initiatives',
  vibeMetricFilter: 'all',
  activePlanWeekStart: localStorage.getItem('spxbi_active_week_start') || '',
  vibeFiltersOpen: false,
  selectedTicketId: null,
  currentUser: '',
  currentUserEmail: '',
  replyingTo: null,
  ntSelectedContribs: [],
  dSelectedContribs: [],
  stSelectedContribs: [],
  wlPopoverOpen: false,
  calYear: new Date().getFullYear(),
  calMonth: new Date().getMonth(),
  calSelectedDate: null,
  isDark: localStorage.getItem('spxbi_theme') !== 'light'
};
